package RateLimiterGateway::Model::GatewayModel;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'GatewaySchema',
    
    connect_info => {
        dsn => 'dbi:SQLite:/tmp/rate_limiter_gateway.db',
        user => '',
        password => '',
    }
);

=head1 NAME

RateLimiterGateway::Model::GatewayModel - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<RateLimiterGateway>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<GatewaySchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.66

=head1 AUTHOR

Eduardo Marques

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
